# -*- coding: utf-8 -*-
"""sirepidemic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F6ozKCO3wJIrQJ06QbTG6fLYkOSDAM1v
"""

# Import Modul yang diperlukan
import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt


# S0 berarti jumlah Suspected awal, I0 berarti jumlah Infected awal, R0 berarti jumlah Recovered awal, dan N adalah jumlah seluruh populasinya.
S0, I0, R0 = 50, 10, 4
N = S0 + I0 + R0


# beta merupakan laju penyebaran infeksi (infectious rate), gamma adalah laju penyembuhan (recovery rate)
beta, gamma = 0.4, 0.05


# Nilai t dalam 30 hari
t = np.linspace(0, 30, 30)


# Rumus model diferensial SIR
def deriv(y, t, N, beta, gamma):
    S, I, R = y
    dSdt = -beta * S * I / N
    dIdt = beta * S * I / N - gamma * I
    dRdt = gamma * I
    return dSdt, dIdt, dRdt


# Vektor awal
y0 = S0, I0, R0


# Integral persamaan SIR terhadap waktu
ret = odeint(deriv, y0, t, args=(N, beta, gamma))
S, I, R = ret.T


# Data plot pada tiga kurva terpisah untuk S(t), I(t) and R(t)
plt.figure(num="SIR Model", facecolor='w')
plt.plot(t, S, 'b', label='Susceptible')
plt.plot(t, I, 'r', label='Infected')
plt.plot(t, R, 'g', label='Recovered')
plt.xlabel('Hari')
plt.ylabel('Populasi')
plt.xlim(0, 30)
plt.ylim(0, 60)
legend = plt.legend()
plt.show()